"""Image-based parser - parses JSON data generated from image analysis."""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from .base import BaseParser, ParseResult, register_parser


class ImageParser(BaseParser):
    """Parse JSON test case data (typically generated by AI agent analyzing images)."""

    format_name = "image"

    def parse(self, content: str, source: str = "") -> ParseResult:
        result = ParseResult(source=source, fmt="image")
        try:
            data = json.loads(content)
        except json.JSONDecodeError as e:
            result.warn(f"Invalid JSON: {e}")
            return result

        if not isinstance(data, list):
            result.warn("Expected JSON array of records")
            return result

        for item in data:
            if isinstance(item, dict):
                result.add_record(item)

        return result

    def parse_file(self, path: str | Path) -> ParseResult:
        p = Path(path)

        if p.is_file() and p.suffix.lower() == ".json":
            content = p.read_text(encoding="utf-8")
            return self.parse(content, source=str(p))

        if p.is_dir():
            return self._scan_images(p)

        result = ParseResult(source=str(p), fmt="image")
        result.warn(f"Unsupported path: {p}")
        return result

    def _scan_images(self, folder: Path) -> ParseResult:
        """Scan folder for image files, return metadata for agent processing."""
        result = ParseResult(source=str(folder), fmt="image")
        supported = {".png", ".jpg", ".jpeg", ".bmp"}
        images = sorted(
            [f for f in folder.iterdir() if f.suffix.lower() in supported],
            key=lambda f: _natural_sort_key(f.name),
        )
        if not images:
            result.warn(f"No supported images found in {folder}")
            return result

        result.meta["images"] = [str(f) for f in images]
        result.meta["image_count"] = len(images)
        return result


def _natural_sort_key(name: str) -> list:
    """Generate sort key for natural ordering (1.png, 2.png, 10.png)."""
    return [int(s) if s.isdigit() else s.lower() for s in re.split(r"(\d+)", name)]


register_parser("image", ImageParser)
